repos:
-   repo: https://github.com/python/black
    rev: 19.10b0
    hooks:
    -   id: black
        language_version: python3.6
        args:
            - --skip-string-normalization
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.7
    hooks:
    -   id: flake8
        language: python_venv
        additional_dependencies: [flake8-comprehensions>=3.1.0]
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.21
    hooks:
    -   id: isort
        language: python_venv
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.730
    hooks:
     -  id: mypy
        args:
          - --no-check-untyped-defs
          - --follow-imports
          - skip
